config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create,:edit, :update, :show] do
    resources :reviews, only: [:index,:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'GiVe tHaT qUaLiTy StUFf'
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'FiNaLly YoU gOt ShIt RiGhT.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'GeT RiD oF tHaT sHiT!.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:index, :new, :create]

  def index
    @reviews = Review.where(restaurant_id: @restaurant)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "Albert stinks real bad" %>
    <%= f.input :category, placeholder: "yh, its not human (out of 'chinese', 'italian', japanese, 'french' and 'belgian')" %>
    <%= f.input :address, placeholder: "probably something serious" %>
    <%= f.input :phone_number, placeholder: "must be something medical"%>

    <%= f.submit "Add", class: "btn btn-secondary" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1> FiNaLly GeT iT rIgHt</h1>
<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

    <% @restaurants.each do |restaurant| %>
       <ul>
        <h2><%= restaurant.name %></h2>
        <p>
          <%= restaurant.category %>,

          <%= link_to 'LEt mE sEe tHaT sHiT', restaurant %>
        </p>

      </ul>
    <% end %>

app/views/restaurants/new.html.erb
<h1>GiVe Me SoMe GoOd StUfF:</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
<p>
  <strong>category:</strong>
  <%= @restaurant.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>
<p>
  <strong>Tel.:</strong>
  <%= @restaurant.phone_number %>
</p>
<%= link_to "add a rating", new_restaurant_review_path(@restaurant) %>
<h3>Reviews:</h3>
<% @restaurant.reviews.each do |review| %>
  <li><%= review.content %>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <div class="form-inputs">
  <%= f.input :content, placeholder: "be creative, be inspired , be high" %>
  <%= f.input :rating, placeholder: "Add a rating (1-5)" %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
    <%= f.submit "Add", class: "btn btn-secondary" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<h1>LoOk At ThAt:</h1>

<ol>
<% @reviews.each do |r| %>
  <li><%= r.content %> (Rating: <%= r.rating %>)</li>
<% end %>
</ol>


<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>WhAt Do YoU tHiNk:</h1>
<%= render 'form', restaurant: @restaurant, review: @review %>

<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>